packageName: eclipse-che-preview-openshift
channels:
- name: stable
  currentCSV: eclipse-che-preview-openshift.v7.0.0-rc-2.0
- name: nightly
  currentCSV: eclipse-che-preview-openshift.v0.0.0-nightly.1561994908
defaultChannel: stable
